### **4. .github/workflows/load-test.yml**  
```yaml
name: African Network Simulation

on: [push]

jobs:
  load-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Simulate 3G Network
        uses: addsp/loadtest-action@v2
        with:
          script: workflows/load-testing/zongwe/simulate.js
          network: '3g' # Throttles to 1.6Mbps down/768Kbps up
          vus: 100 
          duration: 10m
      - name: Publish Results
        uses: actions/upload-artifact@v3
        with:
          name: load-test-report
          path: reports/